### ISSUE TITLE
Performance issue and a possible fix

### ISSUE THREAD

**Issue by StaffiiVR** [Wurielle/izabela-desktop#21]
So if you use the app over a extended period of time, it will get laggyer by the minute, aka i suggest have a button in the settings so you disable the log completely. Since I'm pretty sure its the log that is fucking it up, i cannot think of anything else that might be the issue, i use the app everyday and its annoying when it starts to bug out and everything acts delayed and laggy, also maybe a button to not have it see though would be nice like a darkmode. ^-^

Specs incase you are curious or tell me its my pc
i-7 6700
Gtx 1080 Strix
16gb ram

**Comment by Wurielle** [comment]
Hello @StaffTroll! Thank you for reporting the issue!

I'm investigating a similar issue but I didn't have any luck reproducing it.
I'm working on a new build at the moment and I disabled the logs as it could somewhat explain some lag.
Are you using a HDD, SHDD, SSD or something else as primary drive?

Thank you for sharing a solution, I'll let you know when the build is ready so you can see if it fixes the lag for you.

**Comment by Wurielle** [comment]
Hello again @StaffTroll, I released a [new version](https://github.com/wurielle/izabela-desktop/releases/tag/v0.7.0) of the application containing a few improvements performance-wise.

Following your advice I removed the logs and also added an option to disable the circle animation (this greatly improves performances and is more of an eye-candy than anything). It's available under the "Performance" tab in the options. 
![image](https://user-images.githubusercontent.com/15323067/73217580-7e4b1a00-4158-11ea-80a1-5c966a1d1080.png)

Please let me know if it helped. If it didn't I'm gonna try to find another solution. Thanks again for trying out the software! Hope it helps!

**Comment by StaffTroll** [comment]
Oh yeah i saw the update hit today, sorry for not being able to respond faster, I am mainly using SSD's have 3 and 2 HDD's but Izabela is on SSD.  

For now i have used it for over 6 soon 7 hours, and it don't feel laggy yet, ill come back tomorrow with more results if it were to start lagging again, but yeah i disabled the animation on top like you said, and its working flawlessly. Thanks for still maintaining this project, this app is really sweet. Also you said you disabled the logs i can still see them could that be since i dident restart after it updated? https://i.imgur.com/sEKjuaF.png
Since its still tracking what I'm writing.
- Hope to hear from you

**Comment by StaffTroll** [comment]
Not sure how to give this video to you but i recorded it happen live it was alright, before i started up my stuff then it just started to chug, could it be since i change my audio inputs? maybe?, when i start SteamVR then my headset turns on and auto switches it to some dumb audio input and i change it back and then it kills Izabela, but now that im trying to recreate it, i cannot manage. but you saw what happens anyways on the task manger in the video so you'll see. Now that i type it goes up but not to 100% and so therefor it dont lag i assume. even tho all my vr apps are still on like before when it lagged.

[Video Google Drive](https://drive.google.com/file/d/1YkSZw2CYs2sH8ajphufehqgNLRP4ykWs/view?usp=drivesdk)

**Comment by StaffTroll** [comment]
I can't be using this program anymore Wurielle, I'm sorry i couldn't help, my CPU has been on 100% for the past week when using this and i feel bad for it, i found a replacement which only maxes at 1.6% cpu usage compared to Izabela's 30-40% usage :/

**Comment by Wurielle** [comment]
Thank you for recording the video! The performance fix I released was concerning the "overlay mode" part of the application since I thought that's where the issue was coming from. Apparently even in regular use you see a peak on CPU performances which is very odd to me. There isn't anything special or anything CPU intensive in that part of the software that could justify that peak. I'm not sure why it would come from the VR setup either but I'll have to investigate. 

Sorry it couldn't satisfy your needs. If I find a solution for that issue I'll let you know. 👍

**Comment by StaffTroll** [comment]
Yes please do since i liked using it a lot! 👍

**Comment by matusli** [comment]
hey there i'd like to jump in, i've updated to 0.9.0 but the issue persists. i've recorded a video of what happens when i try to type, so here you go https://youtu.be/cT5xZ74Hy7I

**Comment by Wurielle** [comment]
@matusli your issue is more related to #24

**Comment by Wurielle** [comment]
@StaffTroll I made some performance improvements since you sent the video. I wasn't able to reproduce the issue at all but I made an improvement regarding the text input which could have fixed your issue. If you ever give it a try again, let me know if you see some improvements. Thanks again!

**Comment by StaffTroll** [comment]
> @StaffTroll I made some performance improvements since you sent the video. I wasn't able to reproduce the issue at all but I made an improvement regarding the text input which could have fixed your issue. If you ever give it a try again, let me know if you see some improvements. Thanks again!

Yeah i actually have been following i check my email every day and i see your update every time, as of right now, my friend Mayrui made an issue post about the text delay on the overlay, so we've been checking it every time you update. But yeah ill check this one and see if it still kills my CPU when using.
Keep it up though, You're really good! I hope we can find this bug and squash it

**Comment by StaffTroll** [comment]
Omg, just realized you added support for downloaded voices, yeah since i have been using a different TTS with a downloaded IVONA voice and now i can use that finally on Izabela dang great job, not sure if it's just since you just released it, but it takes a while to say after i click enter.
